name: Deploy CDK Stack

on:
  push:
    branches:
      - main
      - develop
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          pip install -r requirements.txt

      # 👉 Dynamic environment mapping based on branch
      - name: Set deployment environment
        id: setenv
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "DEPLOY_ENVIRONMENT=production" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "staging" ]; then
            echo "DEPLOY_ENVIRONMENT=staging" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "develop" ]; then
            echo "DEPLOY_ENVIRONMENT=dev" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENVIRONMENT=dev" >> $GITHUB_ENV  # fallback
          fi

      - name: Deploy CDK Stack
        env:
          DEPLOY_ENVIRONMENT: ${{ env.DEPLOY_ENVIRONMENT }}
        run: |
          echo "Deploying to environment: $DEPLOY_ENVIRONMENT"
          cdk deploy --context env=$DEPLOY_ENVIRONMENT
